# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('mid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mlength', models.CharField(max_length=10)),
                ('win_radiant', models.BooleanField(default=True)),
                ('rad_teamid', models.CharField(default='novalue', max_length=10)),
                ('dire_teamid', models.CharField(default='novalue', max_length=10)),
                ('rad1_heroid', models.CharField(default='novalue', max_length=10)),
                ('rad2_heroid', models.CharField(default='novalue', max_length=10)),
                ('rad3_heroid', models.CharField(default='novalue', max_length=10)),
                ('rad4_heroid', models.CharField(default='novalue', max_length=10)),
                ('rad5_heroid', models.CharField(default='novalue', max_length=10)),
                ('rad1_playerid', models.CharField(default='novalue', max_length=10)),
                ('rad2_playerid', models.CharField(default='novalue', max_length=10)),
                ('rad3_playerid', models.CharField(default='novalue', max_length=10)),
                ('rad4_playerid', models.CharField(default='novalue', max_length=10)),
                ('rad5_playerid', models.CharField(default='novalue', max_length=10)),
                ('dire1_heroid', models.CharField(default='novalue', max_length=10)),
                ('dire2_heroid', models.CharField(default='novalue', max_length=10)),
                ('dire3_heroid', models.CharField(default='novalue', max_length=10)),
                ('dire4_heroid', models.CharField(default='novalue', max_length=10)),
                ('dire5_heroid', models.CharField(default='novalue', max_length=10)),
                ('dire1_playerid', models.CharField(default='novalue', max_length=10)),
                ('dire2_playerid', models.CharField(default='novalue', max_length=10)),
                ('dire3_playerid', models.CharField(default='novalue', max_length=10)),
                ('dire4_playerid', models.CharField(default='novalue', max_length=10)),
                ('dire5_playerid', models.CharField(default='novalue', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(default='novalue', max_length=10)),
                ('tindex', models.CharField(default='novalue', max_length=10)),
                ('tname', models.CharField(default='novalue', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_inventories', to='stats.Match'),
        ),
    ]
