# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20180204_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_radiant', models.BooleanField(default=True)),
                ('rad1_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rad2_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rad3_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rad4_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rad5_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rad1_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('rad2_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('rad3_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('rad4_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('rad5_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dire1_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dire2_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dire3_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dire4_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dire5_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('dire1_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dire2_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dire3_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dire4_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dire5_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Match')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='match',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='t_name',
            new_name='tname',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='player',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
