# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180321_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dire_teamid',
            field=models.CharField(default='novalue', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='mid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='mlength',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='rad_teamid',
            field=models.CharField(default='novalue', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tid',
            field=models.CharField(default='novalue', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tindex',
            field=models.CharField(default='novalue', max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tname',
            field=models.CharField(default='novalue', max_length=255),
        ),
    ]
