# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180321_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='id',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
