# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sides',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='dire1_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire1_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire2_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire2_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire3_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire3_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire4_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire4_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire5_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire5_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='dire_teamid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad1_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad1_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad2_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad2_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad3_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad3_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad4_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad4_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad5_heroid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad5_playerid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='rad_teamid',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='win_radiant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='mid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='mlength',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tindex',
            field=models.CharField(default='novalue', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tname',
            field=models.CharField(default='novalue', max_length=30),
        ),
        migrations.DeleteModel(
            name='Sides',
        ),
    ]
