# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20180702_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('match', 'playerid'), ('match', 'heroid')]),
        ),
    ]
