# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20180704_0146'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='player',
            name='match',
        ),
    ]
