# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20180704_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='stats.Match'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('match', 'heroid'), ('match', 'playerid')]),
        ),
    ]
