# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20180704_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Match'),
        ),
    ]
