# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_auto_20180704_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='mlength',
        ),
    ]
