# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.DecimalField(decimal_places=0, max_digits=11)),
                ('mlength', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('radiant_side', models.BooleanField(default=True)),
                ('win', models.BooleanField(default=True)),
                ('ally1_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ally1_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ally2_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ally2_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ally3_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ally3_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ally4_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ally4_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('enemy1_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('enemy1_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('enemy2_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('enemy2_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('enemy3_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('enemy3_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('enemy4_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('enemy4_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('enemy5_heroid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('enemy5_playerid', models.DecimalField(decimal_places=0, max_digits=4)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tid', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
                ('tindex', models.DecimalField(decimal_places=0, max_digits=11)),
                ('t_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='testGames',
        ),
        migrations.AddField(
            model_name='inventory',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_inventories', to='stats.Match'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_items', to='stats.Player'),
        ),
    ]
