# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20180205_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stats.Tournament'),
            preserve_default=False,
        ),
    ]
