# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180312_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='mid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
