# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20180312_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
