# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20180312_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament',
            new_name='Tournamente',
        ),
    ]
